---
all:
  hosts:
    jenkins-master-1:
      ansible_host: 89.169.133.11
      ansible_become: true
      ansible_hostname: fhmaa7vav7mm1t3cu46p 
    jenkins-agent-1:
      ansible_host: 158.160.68.104
      ansible_become: true
      ansible_hostname: epdjifo8u3f2d70e1ift
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-1:
        jenkins_agents:
          hosts:
              jenkins-agent-1:
  vars:
    ansible_connection_type: paramiko
    ansible_user: ubuntu
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'