---
all:
  hosts:
    jenkins-master-1:
      ansible_host: 89.169.136.119
    jenkins-agent-1:
      ansible_host: 89.169.161.211
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-1:
        jenkins_agents:
          hosts:
              jenkins-agent-1:
  vars:
    ansible_become: true
    ansible_connection_type: paramiko
    ansible_user: ubuntu
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
