---
all:
  hosts:
    sonar-01:
      ansible_host: 62.84.124.28
    nexus-01:
      ansible_host: 51.250.101.68
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: centos
